### PR TITLE
travis: hhvm added, clear structure

### PR DESCRIPTION
**Pull request by TomasVotruba**
If there is hhvm-nightly, there should be hhvm as well.

Also changed spaces to more readable and standard ones.

### CODE REVIEW

**Comment by dunglas** [comment]
First of all, thanks for your contribution!

Because of a bug in the reflection system of HHVM, some tests related to the Hydra documentation fail. Can you add hvvm to the `allow_failure` section?

**Comment by TomasVotruba** [comment]
Sure, added!

**Comment by dunglas** [comment]
Thank you @TomasVotruba

**Comment by TomasVotruba** [comment]
Thanks

**Pull request merged**
