### PR TITLE
Fix Travis

### PR DESCRIPTION
**Pull request by dunglas**
Tests pass locally but not in Travis.

### CODE REVIEW

**Comment by sroze** [comment]
@dunglas sure that they pass locally ? If I well remember this error come from a broken symfony 2.7-dev.

**Comment by dunglas** [comment]
Maybe I've not the latest version.

Envoyé de mon iPhone

**Comment by dunglas** [comment]
I cannot reproduce the problem locally even after deleting and downloading again my vendors. Strange issue.

**Comment by sroze** [comment]
`composer self-update` before you're `composer update` ?

**Comment by dunglas** [comment]
yes

**Comment by sroze** [comment]
@dunglas Right now you're `composer self-update` is run after the `composer update` ? Can you try using `before_install` rather than `before_script` in the `.travis.yml` file to update composer **before** installing your dependencies ?

**Comment by dunglas** [comment]
My bad. I missed to `git add` a newly created file...

**Comment by sroze** [comment]
@dunglas not merged ?

**Comment by dunglas** [comment]
No. The failure was not related with Travis but was caused by a missing file.

Envoyé de mon iPhone

**Pull request closed without merging**
